### ISSUE TITLE
Add a "swagger viewer" service to the "advanced" demonstration

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-aws-ecscli-demo#35]
**Is your feature request related to a problem? Please describe.**
Currently when using Swagger to look at the provisioned Senzing API server, CORS issues appear.

**Describe the solution you'd like**
Figure out how to support Swagger Viewer.

Note, simply standing up a `swaggerapi/swagger-ui` docker container might not be sufficient as AWS ECS has different IP addresses for different `tasks`.

**Comment by christianswanepoel** [comment]
Is there an ETA for this feature?

**Comment by docktermj** [comment]
Not at the moment, but I'll try to get it in by the end of the week.

**Comment by docktermj** [comment]
@christianswanepoel I have Swagger UI coded in a  the `issue-35.dockter.1` branch.  The documentation can currently be seen at https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/issue-35.dockter.1/docs/advanced/README.md  However, I haven't tested it yet.

I'll be testing it within the next 4 workdays,  but if you feel adventurous,  you can give it a try from the branch.

**Comment by christianswanepoel** [comment]
I will see if I have adventure time - thank you

**Comment by docktermj** [comment]
@christianswanepoel  We are deprecating this repository and will archive it (i.e. make it read-only) in the near future.

**Comment by docktermj** [comment]
Closed due to deprecated repository.
