### ISSUE TITLE
SyntaxError launching G2Command.py on Fargate Cluster Task

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/docker-compose-aws-ecscli-demo#37]
**Describe the bug**
I get a SyntaxError: invalid syntax executing python G2Command.py

**Full error**
```
File "G2Command.py", line 387
    printWithNewLines(f'G2Exception: {ex}', 'B')
                                         ^
SyntaxError: invalid syntax
```

**To Reproduce**
```
ssh root@my-Fargate-Cluster-SSHD-Task-ip
cd /opt/senzing/g2/python 
python G2Command.py

```
**Expected behaviour**
I am wanting to use G2Command.py to run purgeRepository - hoping it will clear all database entries in Snenzing(?)

**Comment by antaenc** [comment]
Hi Christian, 
Can you do:

- python --version
- Then change python G2Command.py to python3 G2Command.py (or just run ./G2Command.py)

**Comment by christianswanepoel** [comment]
Hi See output
`python --version
Python 2.7.16`
`python G2Command.py
  File "G2Command.py", line 387
    printWithNewLines(f'G2Exception: {ex}', 'B')`
`python3 G2Command.py
ERROR: Environment variable SENZING_ROOT is not set. Did you remember to setup your environment by sourcing the setupEnv file?`

Ok so then I do the following:
`find / -name setupEnv
/opt/senzing/g2/resources/templates/setupEnv`
`cd /opt/senzing/g2/resources/templates/`
`source setupEnv`

And finally:
`cd /opt/senzing/g2/python
python3 G2Command.py
ERROR: G2Module.ini is missing from the search path location(s). Searched:
	/opt/senzing/g2/python
	etc

Traceback (most recent call last):
  File "G2Command.py", line 2489, in <module>
    ini_file_name = pathlib.Path(G2Paths.get_G2Module_ini_path()) if not args.iniFile else pathlib.Path(args.iniFile[0]).resolve()
  File "/opt/senzing/g2/python/G2Paths.py", line 40, in get_G2Module_ini_path
    return __get_file_path('G2Module.ini')
  File "/opt/senzing/g2/python/G2Paths.py", line 76, in __get_file_path
    raise FileNotFoundError(f'[Errno {errno.ENOENT}] {os.strerror(errno.ENOENT)}: {filename} - {msg_args}')
FileNotFoundError: [Errno 2] No such file or directory: G2Module.ini - Use command line argument -c (--inifile) to specify the path & filename for G2Module.ini.`

**Comment by christianswanepoel** [comment]
Ok it would seem the environment vars setupEnv is expecting doesn't exist...
```
env |grep SENZING
SENZING_ROOT=
SENZING_CONFIG_FILE=/G2Module.ini
```
So my assumption is that the senzing/sshd image included in docker-compose-aws-ecscli-demo > advanced isn't configured to be used for running the Python scripts?

**Comment by docktermj** [comment]
Hi Christian!

That is correct.   

We built it just so "scp" could be used to transfer files.   ....we didn't think through all of the implications for "ssh".

Can you open up an issue in https://github.com/Senzing/docker-sshd/issues to support Senzing command line programs?

(We treat customer initiated issues with more priority than internally created issues)

**Comment by docktermj** [comment]
@christianswanepoel   You can use the docker-bin/senzing-console.sh or docker-bin/senzing-xterm.sh commands to have the environment set up for you.

**Comment by christianswanepoel** [comment]
I am not sure what you mean - should I instal new tasks into my Fargate cluster with docker-bin/senzing-console.sh, as these commands aren't on sshd either? 

I don't want to install xterm for security reasons and want a real terminal.

**Comment by docktermj** [comment]
@christianswanepoel   I see what we need to change.  In the meantime, when you `ssh` into the the `senzing/sshd` docker container, just run the following to get the Senzing command-line programs to work

```console
export LD_LIBRARY_PATH=/opt/senzing/g2/lib:/opt/senzing/g2/lib/debian:/opt/IBM/db2/clidriver/lib
export ODBCSYSINI=/etc/opt/senzing
export PATH=${PATH}:/opt/senzing/g2/python:/opt/IBM/db2/clidriver/adm:/opt/IBM/db2/clidriver/bin
export PYTHONPATH=/opt/senzing/g2/python
export SENZING_ETC_PATH=/etc/opt/senzing
```

**Comment by docktermj** [comment]
### Notes for Senzing developers:

In `senzing/senzing-base:1.5.2`, the environment variables are set for "USER 1001"
https://github.com/Senzing/docker-senzing-base/blob/master/Dockerfile#L62-L70

We also need to set the environment variables for the `root` user.

**Comment by docktermj** [comment]
@christianswanepoel   I've updated the container to `senzing/sshd:1.0.1` which now has the environment variables set for Senzing when ssh-ing into the container.

You can either get an updated version of `docker-compose-aws-ecscli-demo`:

```
cd ~/senzing.git/docker-compose-aws-ecscli-demo
git pull
```

Or you can just update the following line:
https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/58b7b6949af026a79fe8b0ed8d1b0f2bbb58a5bb/resources/advanced/docker-compose-sshd.yaml#L4

So that `senzing/sshd:1.0.1` is used.

Let me know if that provides what you need.

**Comment by christianswanepoel** [comment]
> @christianswanepoel I see what we need to change. In the meantime, when you `ssh` into the the `senzing/sshd` docker container, just run the following to get the Senzing command-line programs to work
> 
> ```
> export LD_LIBRARY_PATH=/opt/senzing/g2/lib:/opt/senzing/g2/lib/debian:/opt/IBM/db2/clidriver/lib
> export ODBCSYSINI=/etc/opt/senzing
> export PATH=${PATH}:/opt/senzing/g2/python:/opt/IBM/db2/clidriver/adm:/opt/IBM/db2/clidriver/bin
> export PYTHONPATH=/opt/senzing/g2/python
> export SENZING_ETC_PATH=/etc/opt/senzing
> ```

I found it easiest to edit ~/.bashrc and add the above vars, as it's non-trivial to add new services to an existing cluster, especially that I have a Production and Development cluster running.

Thank you (as always) for the prompt feedback.

**Comment by docktermj** [comment]
@christianswanepoel   You nailed it! That's exactly what I did in the fix.  
https://github.com/Senzing/docker-sshd/blob/b7bd4c09fd57890f85ac3c69dd0a8c9edab22d97/Dockerfile#L75-L79

**Comment by docktermj** [comment]
@christianswanepoel Can you verify that it now works correctly for you?

**Comment by docktermj** [comment]
@christianswanepoel Can this issue be considered closed?

If so, please close it.   If I don't hear from you in 7 days, I'll go ahead and close it.
