### ISSUE TITLE
Got error when attempting to "Delete tasks definitions" on advanced-cluster

### ISSUE THREAD

**Issue by oskar700** [Senzing/docker-compose-aws-ecscli-demo#43]
**Describe the bug**
I ran this command on the command line:

> for SENZING_ECS_TASK_DEFINITION in ${SENZING_ECS_TASK_DEFINITIONS[@]};\
do \
  aws ecs deregister-task-definition \
    --task-definition $( \
      aws ecs list-task-definitions \
        --family-prefix "${SENZING_AWS_PROJECT}-project-name-${SENZING_ECS_TASK_DEFINITION}" \
      | jq --raw-output .taskDefinitionArns[0] \
    ) > /dev/null; \
done

and got error:
>An error occurred (InvalidParameterException) when calling the DeregisterTaskDefinition operation: Revision is missing

I also noticed the directions are missing a couple of services in the "Delete services" section.
Also, 2 of the database deletions are missing from "Delete Aurora PostgreSQL" section.

**To Reproduce**
Follow the directions at
`https://github.com/Senzing/docker-compose-aws-ecscli-demo/tree/master/docs/advanced-cluster#cleanup`
and the errors will come up.

**Expected behavior**
The steps execute without errors and no steps are missing.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by docktermj** [comment]
@oskar700 We are deprecating this repository and will archive it (i.e. make it read-only) in the near future.

**Comment by docktermj** [comment]
Closed due to deprecated repository.
