### ISSUE TITLE
Incorrect governor database url for clustered setup

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/docker-compose-aws-ecscli-demo#57]
**Describe the bug**
There is only 1 governor database url configured for the clustered setup. It should be using all 3 urls for the core, libfeat and res databases

**To Reproduce**
On line https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/master/resources/advanced-cluster/docker-compose-stream-loader.yaml#L45, it has url to connect to only 1 host db. Similarly in the redoer

**Expected behavior**
There should be 3 urls on line https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/master/resources/advanced-cluster/docker-compose-stream-loader.yaml#L45 one for each db host in clustered setup

**Additional context**

**Comment by docktermj** [comment]
@ssasidharanwp We are deprecating this repository and will archive it (i.e. make it read-only) in the near future.

**Comment by docktermj** [comment]
Closed due to deprecated repository.
