### ISSUE TITLE
Missing dead letter queue in stream loader

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/docker-compose-aws-ecscli-demo#58]
**Describe the bug**
The `SENZING_SQS_FAILURE_QUEUE_URL` parameter is missing in the stream loader config in the file: https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/master/resources/advanced-cluster/docker-compose-stream-loader.yaml

**Comment by docktermj** [comment]
@ssasidharanwp We are deprecating this repository and will archive it (i.e. make it read-only) in the near future.

**Comment by docktermj** [comment]
Closed due to deprecated repository.
