### ISSUE TITLE
Support for redoer loader and redoer producer

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/docker-compose-aws-ecscli-demo#59]
**Is your feature request related to a problem? Please describe.**
We are currently using this repository for our deployment. Since this is missing the redoer loader and redoer producer yaml files , we created them based on your instructions to use redoer yaml as the base. It would be great if you could support the loader and producer yaml files that way we wont have manually check and add any changes made to redoer yaml. 

**Describe the solution you'd like**
Add the redoer loader and producer yaml files for advanced cluster https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/master/resources/advanced-cluster/

**Comment by docktermj** [comment]
@ssasidharanwp We are deprecating this repository and will archive it (i.e. make it read-only) in the near future.

**Comment by docktermj** [comment]
Closed due to deprecated repository.
