### ISSUE TITLE
Advanced cluster stream loader mem and cpu limits from env

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/docker-compose-aws-ecscli-demo#60]
**Is your feature request related to a problem? Please describe.**
The current defaults on the stream loader ecs yaml(https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/master/resources/advanced-cluster/ecs-params-stream-loader.yaml#L7) of 1 cpu and 8GB memory causes the containers to crash after running for sometime. When a lot of these crash , they are re-created but again have to wait for loading the efs and then start. It would nice to have 2 environment variables to configure this

**Describe the solution you'd like**
2 environment variables(maybe SENZING_STREAM_LOADER_MEMORY and SENZING_STREAM_LOADER_CPU) to set the memory and cpu values for stream loader and them being used in the yaml: https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/master/resources/advanced-cluster/ecs-params-stream-loader.yaml#L7

**Describe alternatives you've considered**
Edit files manually before deploy

**Comment by docktermj** [comment]
@ssasidharanwp We are deprecating this repository and will archive it (i.e. make it read-only) in the near future.

**Comment by docktermj** [comment]
Closed due to deprecated repository.
