### ISSUE TITLE
Env variable to disable public ip

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/docker-compose-aws-ecscli-demo#61]
**Is your feature request related to a problem? Please describe.**
We use https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/master/resources/advanced-cluster/ for our deployment. Currently all services have a public IP enabled. We would like to use it wth public IP disabled for security purposes. Can you please add an env variable that can be used to set these to DISABLED

**Describe the solution you'd like**
Add an env variable(maybe SENZING_AWS_ASSIGN_PUBLIC_IP) which can be set to `ENABLED/DISABLED` and use that in all services under https://github.com/Senzing/docker-compose-aws-ecscli-demo/tree/master/resources/advanced-cluster/

**Describe alternatives you've considered**
Edit manually each file before deploying

**Comment by docktermj** [comment]
@ssasidharanwp We are deprecating this repository and will archive it (i.e. make it read-only) in the near future.

**Comment by docktermj** [comment]
Closed due to deprecated repository.
